---

- name: Manage database(s)
  mysql_db:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_user: "{{ item.login_user | default('') }}"
    login_password: "{{ item.login_password | default('')}}"
    login_port: "{{ item.login_port | default('3306') }}"
  with_items: "{{ mysql_databases }}"
