---

- name: Install MySQL dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ mysql_dependencies }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ mysql_pip_packages }}"
